const Model = {
  "banner": [
    {
      "avatar": "",
      "color": "4EAE8E",
      "commentSwitch": false,
      "content": "",
      "itemPicUrl": "",
      "leftTopTag": "",
      "linkUrl": "",
      "nickname": "",
      "period": "",
      "picList": [],
      "picUrl": "https://yanxuan.nosdn.127.net/c646886fdf9abe1c69c4267380137ccc.jpg",
      "priceInfo": 0,
      "readCount": "",
      "scenePicUrl": "",
      "schemeUrl": "http://m.you.163.com/act/topic/v1/pub/FAuWzWVkVl.html",
      "subTitle": "满99任选5件",
      "subtitle": "",
      "tagInfo": "",
      "title": "那些点亮餐桌的 高颜值餐具",
      "topicId": 0,
      "topicTagId": 0,
      "topicTemplateId": 0,
      "type": -1,
      "typeName": ""
    },
    {
      "avatar": "",
      "color": "cfb290",
      "commentSwitch": false,
      "content": "",
      "itemPicUrl": "",
      "leftTopTag": "",
      "linkUrl": "",
      "nickname": "",
      "period": "",
      "picList": [],
      "picUrl": "https://yanxuan.nosdn.127.net/42a74ba5f1579e7f871ce293085c8b62.jpg",
      "priceInfo": 0,
      "readCount": "",
      "scenePicUrl": "",
      "schemeUrl": "http://m.you.163.com/topic/v1/pub/1Bnuwj1DvE.html",
      "subTitle": "满199减30",
      "subtitle": "",
      "tagInfo": "",
      "title": "秋冬搭配 气质女士篇",
      "topicId": 0,
      "topicTagId": 0,
      "topicTemplateId": 0,
      "type": -1,
      "typeName": ""
    },
    {
      "avatar": "",
      "color": "725c55",
      "commentSwitch": false,
      "content": "",
      "itemPicUrl": "",
      "leftTopTag": "",
      "linkUrl": "",
      "nickname": "",
      "period": "",
      "picList": [],
      "picUrl": "https://yanxuan.nosdn.127.net/4ce3cb5f30096afb187d131abd9c0e1e.jpg",
      "priceInfo": 0,
      "readCount": "",
      "scenePicUrl": "",
      "schemeUrl": "http://m.you.163.com/topic/v1/pub/g6N7DqdGRc.html",
      "subTitle": "43款鞋靴特价中",
      "subtitle": "",
      "tagInfo": "",
      "title": "你需要一双战靴 走天下",
      "topicId": 0,
      "topicTagId": 0,
      "topicTemplateId": 0,
      "type": -1,
      "typeName": ""
    },
    {
      "avatar": "",
      "color": "C9A78C",
      "commentSwitch": false,
      "content": "",
      "itemPicUrl": "",
      "leftTopTag": "",
      "linkUrl": "",
      "nickname": "",
      "period": "",
      "picList": [],
      "picUrl": "https://yanxuan.nosdn.127.net/48f7fc275398b6cb48aa670e896f6dd6.jpg",
      "priceInfo": 0,
      "readCount": "",
      "scenePicUrl": "",
      "schemeUrl": "http://m.you.163.com/topic/v1/pub/CRm8DJa2Si.html",
      "subTitle": "格纹系列特价中",
      "subtitle": "",
      "tagInfo": "",
      "title": "时髦宝贝 都穿格纹入秋",
      "topicId": 0,
      "topicTagId": 0,
      "topicTemplateId": 0,
      "type": -1,
      "typeName": ""
    },
    {
      "avatar": "",
      "color": "B7A078",
      "commentSwitch": false,
      "content": "",
      "itemPicUrl": "",
      "leftTopTag": "",
      "linkUrl": "",
      "nickname": "",
      "period": "",
      "picList": [],
      "picUrl": "https://yanxuan.nosdn.127.net/74373b06b38aa134e2df9f8d017370b6.jpg",
      "priceInfo": 0,
      "readCount": "",
      "scenePicUrl": "",
      "schemeUrl": "http://m.you.163.com/topic/v1/pub/0ME2BpIts5.html",
      "subTitle": "黑白好物推荐",
      "subtitle": "",
      "tagInfo": "",
      "title": "永不过时的 黑白经典",
      "topicId": 0,
      "topicTagId": 0,
      "topicTemplateId": 0,
      "type": -1,
      "typeName": ""
    }
  ],
  "column": [
    {
      "articleCount": "250篇文章",
      "linkUrl": "",
      "picUrl": "https://yanxuan.nosdn.127.net/254e04f823354c67d765d68c4012b64e.png",
      "schemeUrl": "",
      "title": "严选推荐",
      "topicId": "0",
      "type": 0
    },
    {
      "articleCount": "107篇文章",
      "linkUrl": "",
      "picUrl": "https://yanxuan.nosdn.127.net/1662ac1fabbc2e495bdda39357a93d65.png",
      "schemeUrl": "",
      "title": "挑款师推荐",
      "topicId": "0",
      "type": 1
    },
    {
      "articleCount": "34篇文章",
      "linkUrl": "",
      "picUrl": "https://yanxuan.nosdn.127.net/cbcc9dcba30d4f8448a4412db4d9122f.png",
      "schemeUrl": "",
      "title": "丁磊私物推荐",
      "topicId": "0",
      "type": 2
    },
    {
      "articleCount": "182篇文章",
      "linkUrl": "",
      "picUrl": "https://yanxuan.nosdn.127.net/7be4ed9901fd6b110158e3381eb67ae2.png",
      "schemeUrl": "http://m.you.163.com/topic/v1/look/list",
      "title": "严选LOOK",
      "topicId": "0",
      "type": -1
    },
    {
      "articleCount": "5篇文章",
      "linkUrl": "",
      "picUrl": "https://yanxuan.nosdn.127.net/53cef980b13b1b20998d317989b184a1.png",
      "schemeUrl": "",
      "title": "口碑商品",
      "topicId": "0",
      "type": 3
    },
    {
      "articleCount": "2篇文章",
      "linkUrl": "",
      "picUrl": "https://yanxuan.nosdn.127.net/e85c371f75223deb8a65b1f4cf64feb7.png",
      "schemeUrl": "",
      "title": "特色系列",
      "topicId": "0",
      "type": 4
    },
    {
      "articleCount": "6篇文章",
      "linkUrl": "",
      "picUrl": "https://yanxuan.nosdn.127.net/8aa454c29a80d4525fff278defce73ce.png",
      "schemeUrl": "",
      "title": "严选全球",
      "topicId": "0",
      "type": 6
    }
  ],
  "findMore": [
    {
      "avatar": "",
      "color": "",
      "commentSwitch": false,
      "content": "连续下了几场雨，杭州的早晚，已透出几丝凉意。再睡席子便有点凉了，于是周末从柜子翻出这件全棉针织四件套换上。那会儿它是作为样品来的我家，如今正式的床品都已在线上走过了三季。大家对它的热爱只增不减，如我，总在换季的第一时间想到它。\n\n当初我们跑遍山东、江苏、浙江等地，为寻找合适的纺料奔波不停。棉花的产地要亲自挑选，连棉纤长度的毫米级都要反复和供应商斟酌比对。最后选定的新疆长绒棉纺料，大家都说如内衣一般亲肤柔软，有的人洗完铺上，自己还没来得及躺一躺，就被家中最喜轻柔的猫主子霸占去。\n\n床品不光要舒适，还要够安全，才能经得起裸睡的考验。因此我们放弃了不够环保的传统染料，选用了大品牌的活性染料来印染，不含甲醛和芳香胺等有害物质，对婴儿的娇嫩皮肤尤其友好。分子级的着色，也使床品的色彩朦胧柔和，耐洗磨不褪色。\n\n纯色、条纹2款床品分别拥有5种配色、2个款式、多种规格，可以百搭各式家装风格和床的尺寸。初秋换季，将这款裸睡神器分享给你，愿你秋凉好睡，酣梦相随。",
      "itemPicUrl": "https://yanxuan.nosdn.127.net/15040927525260414.jpg",
      "leftTopTag": "",
      "linkUrl": "http://m.you.163.com/topic/v1/pub/4lVInJbfyh.html",
      "nickname": "",
      "period": "",
      "picList": [
        "https://yanxuan.nosdn.127.net/15040927525260414.jpg",
        "https://yanxuan.nosdn.127.net/15040927586650416.jpg",
        "https://yanxuan.nosdn.127.net/15040927556820415.jpg",
        "https://yanxuan.nosdn.127.net/15040927612050417.jpg",
        "https://yanxuan.nosdn.127.net/15040927635980418.jpg",
        "https://yanxuan.nosdn.127.net/15040927656280419.jpg"
      ],
      "picUrl": "",
      "priceInfo": 0,
      "readCount": "",
      "scenePicUrl": "https://yanxuan.nosdn.127.net/15040927525260414.jpg",
      "schemeUrl": "",
      "subTitle": "连续下了几场雨，杭州的早晚，已透出几丝凉意。再睡席子便有点凉了，于是周末从柜子翻...",
      "subtitle": "连续下了几场雨，杭州的早晚，已透出几丝凉意。再睡席子便有点凉了，于是周末从柜子翻...",
      "tagInfo": "",
      "title": "初秋，最想用它来裸睡",
      "topicId": 770,
      "topicTagId": 0,
      "topicTemplateId": 0,
      "type": 1,
      "typeName": ""
    },
    {
      "avatar": "",
      "color": "",
      "commentSwitch": false,
      "content": "",
      "itemPicUrl": "http://yanxuan.nosdn.127.net/b2610f5507a7768b3ada774a5f590007.png",
      "leftTopTag": "",
      "linkUrl": "http://m.you.163.com/topic/v1/pub/eIRBALhppc.html",
      "nickname": "",
      "period": "",
      "picList": [],
      "picUrl": "",
      "priceInfo": 0,
      "readCount": "",
      "scenePicUrl": "http://yanxuan.nosdn.127.net/2d5f005dd2cbe7c44270517c30545c6e.jpg",
      "schemeUrl": "",
      "subTitle": "来自韩国制造的好物",
      "subtitle": "来自韩国制造的好物",
      "tagInfo": "",
      "title": "严选全球韩国篇",
      "topicId": 958,
      "topicTagId": 0,
      "topicTemplateId": 0,
      "type": 0,
      "typeName": ""
    },
    {
      "avatar": "",
      "color": "",
      "commentSwitch": false,
      "content": "",
      "itemPicUrl": "https://yanxuan.nosdn.127.net/14944908427283682.jpg",
      "leftTopTag": "",
      "linkUrl": "http://m.you.163.com/topic/v1/pub/r08StORWIV.html",
      "nickname": "",
      "period": "",
      "picList": [],
      "picUrl": "",
      "priceInfo": 0,
      "readCount": "",
      "scenePicUrl": "https://yanxuan.nosdn.127.net/14944908411813681.jpg",
      "schemeUrl": "",
      "subTitle": "夏日居家必备",
      "subtitle": "夏日居家必备",
      "tagInfo": "",
      "title": "这双拖鞋，治愈人生",
      "topicId": 337,
      "topicTagId": 0,
      "topicTemplateId": 0,
      "type": 0,
      "typeName": ""
    },
    {
      "avatar": "",
      "color": "",
      "commentSwitch": false,
      "content": "",
      "itemPicUrl": "http://yanxuan.nosdn.127.net/065daf6cf8a2c98d8309717a47a995b1.jpg",
      "leftTopTag": "",
      "linkUrl": "http://m.you.163.com/topic/v1/pub/FAuWzWVkVl.html",
      "nickname": "",
      "period": "",
      "picList": [],
      "picUrl": "",
      "priceInfo": 0,
      "readCount": "",
      "scenePicUrl": "http://yanxuan.nosdn.127.net/e92139526928596ca71a72bbd0530b3f.jpg",
      "schemeUrl": "",
      "subTitle": "满99任选5件，满88任选3件",
      "subtitle": "满99任选5件，满88任选3件",
      "tagInfo": "",
      "title": "那些点亮餐桌的高颜值餐具",
      "topicId": 1026,
      "topicTagId": 0,
      "topicTemplateId": 0,
      "type": 0,
      "typeName": ""
    },
    {
      "avatar": "",
      "color": "",
      "commentSwitch": false,
      "content": "",
      "itemPicUrl": "https://yanxuan.nosdn.127.net/14902390968681677.jpg",
      "leftTopTag": "",
      "linkUrl": "http://m.you.163.com/topic/v1/pub/g3eNigu6Sk.html",
      "nickname": "",
      "period": "",
      "picList": [],
      "picUrl": "",
      "priceInfo": 0,
      "readCount": "",
      "scenePicUrl": "http://yanxuan.nosdn.127.net/a94fd748782ac24c41a900ba57ca3567.jpg",
      "schemeUrl": "",
      "subTitle": "得体生活必修课",
      "subtitle": "得体生活必修课",
      "tagInfo": "",
      "title": "优雅女士穿搭好物",
      "topicId": 20170317,
      "topicTagId": 0,
      "topicTemplateId": 0,
      "type": 0,
      "typeName": ""
    },
    {
      "avatar": "",
      "color": "",
      "commentSwitch": false,
      "content": "",
      "itemPicUrl": "http://yanxuan.nosdn.127.net/2bd51e1d9e6c40a728d946c57a1d9ef2.jpg",
      "leftTopTag": "",
      "linkUrl": "http://m.you.163.com/topic/v1/pub/1Bnuwj1DvE.html",
      "nickname": "",
      "period": "",
      "picList": [],
      "picUrl": "",
      "priceInfo": 0,
      "readCount": "",
      "scenePicUrl": "http://yanxuan.nosdn.127.net/8b52aea32a210a8543828f849f33e706.jpg",
      "schemeUrl": "",
      "subTitle": "页面内满199减30，满399减60",
      "subtitle": "页面内满199减30，满399减60",
      "tagInfo": "",
      "title": "秋冬的质感都在材料上 女士篇",
      "topicId": 993,
      "topicTagId": 0,
      "topicTemplateId": 0,
      "type": 0,
      "typeName": ""
    },
    {
      "avatar": "",
      "color": "",
      "commentSwitch": false,
      "content": "",
      "itemPicUrl": "https://yanxuan.nosdn.127.net/14914437252832832.jpg",
      "leftTopTag": "",
      "linkUrl": "http://m.you.163.com/topic/v1/pub/XA8nqTkX3a.html",
      "nickname": "",
      "period": "",
      "picList": [],
      "picUrl": "",
      "priceInfo": 0,
      "readCount": "",
      "scenePicUrl": "https://yanxuan.nosdn.127.net/14913779653712108.jpg",
      "schemeUrl": "",
      "subTitle": "这些消耗品真的超容易售罄",
      "subtitle": "这些消耗品真的超容易售罄",
      "tagInfo": "",
      "title": "严选到底什么值得囤",
      "topicId": 255,
      "topicTagId": 0,
      "topicTemplateId": 0,
      "type": 0,
      "typeName": ""
    },
    {
      "avatar": "",
      "color": "",
      "commentSwitch": false,
      "content": "护齿这件事，在严选洗护类选品中，一直很受重视。选品至今，我们也总结出不少护齿小妙招，今天是全国爱牙日，来和大家分享心得，希望我们一起，将刷牙变得更简单高效。\n\n牙龈频繁出血或疼痛的人，常被推荐用软毛牙刷，但不少人担心，刷毛过软，清洁力会不够。我们在日本发现的这款抗菌牙刷，便能解决这个问题，刷毛不仅柔软纤长，与牙齿摩擦时，还能产生大量负离子，对去垢很有帮助。\n\n早晨刷牙时间有限，匆匆了事是常事，而科学刷牙，至少要保证2-3分钟。用自带2分钟定时功能的电动牙刷，对控制刷牙时间很有效。处于没睡醒的梦游状态时，它还会隔30秒提醒你换区，懒人们刷牙必备它。\n\n宝宝们不爱刷牙，聪明的爸妈总是应对有招。鲜艳的婴儿专用牙胶牙刷，最能吸引宝宝的注意，长牙初期爱啃咬，硅胶刷毛很安全，咬一咬便能清除食物残渣。对于拒牙膏味道的宝宝，可以给他用无需牙膏的儿童负离子牙刷过渡，仅用清水洗刷，便能达到很好的清洁效果。\n\n另外，将家人的牙刷放在一起，容易交叉传染细菌，一人一杯、合理收纳，才更卫生。我家的牙具，都是放在墙上的吸盘置物架中，既能通风防菌，还不占台面空间。成套的牙刷牙杯放成一排，洗漱时光也变得有爱起来了呢。",
      "itemPicUrl": "https://yanxuan.nosdn.127.net/15058875206852228.jpg",
      "leftTopTag": "",
      "linkUrl": "http://m.you.163.com/topic/v1/pub/JGCOV68DcD.html",
      "nickname": "",
      "period": "",
      "picList": [
        "https://yanxuan.nosdn.127.net/15058875206852228.jpg",
        "https://yanxuan.nosdn.127.net/15058875278622229.jpg",
        "https://yanxuan.nosdn.127.net/15058875306622230.jpg",
        "https://yanxuan.nosdn.127.net/15058875374042231.jpg",
        "https://yanxuan.nosdn.127.net/15058875579772233.jpg"
      ],
      "picUrl": "",
      "priceInfo": 0,
      "readCount": "",
      "scenePicUrl": "https://yanxuan.nosdn.127.net/15058875206852228.jpg",
      "schemeUrl": "",
      "subTitle": "护齿这件事，在严选洗护类选品中，一直很受重视。选品至今，我们也总结出不少护齿小妙...",
      "subtitle": "护齿这件事，在严选洗护类选品中，一直很受重视。选品至今，我们也总结出不少护齿小妙...",
      "tagInfo": "",
      "title": "爱牙日，送你4个护齿小妙招",
      "topicId": 925,
      "topicTagId": 0,
      "topicTemplateId": 0,
      "type": 1,
      "typeName": ""
    },
    {
      "avatar": "",
      "color": "",
      "commentSwitch": false,
      "content": "",
      "itemPicUrl": "http://yanxuan.nosdn.127.net/636f2fa8665073f4fec3acb6353a121b.jpg",
      "leftTopTag": "",
      "linkUrl": "http://m.you.163.com/topic/v1/pub/jVC9xGP9IE.html",
      "nickname": "",
      "period": "",
      "picList": [],
      "picUrl": "",
      "priceInfo": 0,
      "readCount": "",
      "scenePicUrl": "http://yanxuan.nosdn.127.net/8a851cc2dae184dcfeb03434e582d3ad.jpg",
      "schemeUrl": "",
      "subTitle": "像亦舒女郎一样拥有好品味",
      "subtitle": "像亦舒女郎一样拥有好品味",
      "tagInfo": "",
      "title": "都市女郎的生活应该什么样？",
      "topicId": 615,
      "topicTagId": 0,
      "topicTemplateId": 0,
      "type": 0,
      "typeName": ""
    }
  ],
  "hasMore": true,
  "recommendOne": {
    "avatar": "http://yanxuan.nosdn.127.net/ca04bde21352233c9635a90f16c94448.png",
    "color": "",
    "commentSwitch": false,
    "content": "",
    "itemPicUrl": "",
    "leftTopTag": "",
    "linkUrl": "",
    "nickname": "严选推荐",
    "period": "",
    "picList": [],
    "picUrl": "https://yanxuan.nosdn.127.net/ce358fcee3a5eb9dba9bce277a7e9445.jpg",
    "priceInfo": 15,
    "readCount": "",
    "scenePicUrl": "",
    "schemeUrl": "http://m.you.163.com/topic/v1/pub/2lIC03j54O.html",
    "subTitle": "南北生活有多少大不同",
    "subtitle": "",
    "tagInfo": "",
    "title": "最激烈的南北之争即将打响",
    "topicId": 880,
    "topicTagId": 0,
    "topicTemplateId": 0,
    "type": 0,
    "typeName": "严选推荐"
  },
  "recommendThree": {
    "avatar": "https://yanxuan.nosdn.127.net/15078594933011860.png",
    "color": "",
    "commentSwitch": false,
    "content": "",
    "itemPicUrl": "",
    "leftTopTag": "",
    "linkUrl": "",
    "nickname": "丁磊",
    "period": "",
    "picList": [],
    "picUrl": "https://yanxuan.nosdn.127.net/ea6b3cbed0b85d004b3044a5f5671dbd.jpg",
    "priceInfo": 0,
    "readCount": "",
    "scenePicUrl": "",
    "schemeUrl": "http://m.you.163.com/topic/v1/pub/ujC2oS2t99.html",
    "subTitle": "健康生活，果汁必喝天然健康无添加的。网易严选NFC鲜榨果汁，榨汁后瞬间灭菌，直接...",
    "subtitle": "",
    "tagInfo": "",
    "title": "把新鲜水果一口喝掉",
    "topicId": 1024,
    "topicTagId": 0,
    "topicTemplateId": 0,
    "type": 2,
    "typeName": "丁磊私物推荐"
  },
  "recommendTwo": {
    "avatar": "https://yanxuan.nosdn.127.net/15079537486775179.png",
    "color": "",
    "commentSwitch": false,
    "content": "",
    "itemPicUrl": "",
    "leftTopTag": "",
    "linkUrl": "",
    "nickname": "配件组：羊羊",
    "period": "",
    "picList": [],
    "picUrl": "https://yanxuan.nosdn.127.net/70c6379287b31d81d3451cd1a87f8a14.jpg",
    "priceInfo": 0,
    "readCount": "",
    "scenePicUrl": "",
    "schemeUrl": "http://m.you.163.com/topic/v1/pub/QlSyoWHfZW.html",
    "subTitle": "今年时尚界各大品牌的秋冬鞋包中，金属扣的设计几乎无处不在。特别是圆形扣，简约大气...",
    "subtitle": "",
    "tagInfo": "",
    "title": "乐福鞋，趿着穿也时髦",
    "topicId": 1032,
    "topicTagId": 0,
    "topicTemplateId": 0,
    "type": 1,
    "typeName": "挑款师推荐"
  },
  "tenfifteen": [],
  "yxGlobal": {
    "avatar": "http://yanxuan.nosdn.127.net/429b2da980a8fff7460b6b49d8472577.png",
    "color": "",
    "commentSwitch": false,
    "content": "",
    "itemPicUrl": "",
    "leftTopTag": "",
    "linkUrl": "",
    "nickname": "严选日本",
    "period": "",
    "picList": [],
    "picUrl": "https://yanxuan.nosdn.127.net/4a38afac38b2d74373973eb894abb571.png",
    "priceInfo": 9.9,
    "readCount": "",
    "scenePicUrl": "",
    "schemeUrl": "http://m.you.163.com/topic/v1/pub/hjB1aXA93U.html",
    "subTitle": "高颜值餐具、精巧生活用品等日本制造的好物",
    "subtitle": "",
    "tagInfo": "",
    "title": "严选全球日本篇",
    "topicId": 960,
    "topicTagId": 0,
    "topicTemplateId": 0,
    "type": -1,
    "typeName": ""
  },
  "yxLook": {
    "avatar": "https://yanxuan.nosdn.127.net/2f051675169da62ab7869ee0697de4bc",
    "color": "",
    "commentSwitch": false,
    "content": "帽子挺好的",
    "itemPicUrl": "",
    "leftTopTag": "",
    "linkUrl": "",
    "nickname": "K****",
    "period": "",
    "picList": [],
    "picUrl": "https://yanxuan.nosdn.127.net/e388b005201c67b055204405eb7a6243.jpg",
    "priceInfo": 0,
    "readCount": "",
    "scenePicUrl": "",
    "schemeUrl": "http://m.you.163.com/topic/v1/pub/JkmPPzMmvV.html",
    "subTitle": "",
    "subtitle": "",
    "tagInfo": "{\"picUrl\":\"https://yanxuan.nosdn.127.net/e388b005201c67b055204405eb7a6243.jpg\",\"width\":1000,\"comment\":[{\"showIndex\":0,\"positionRight\":true,\"actId\":0,\"itemDesc\":\"Gucci制造商，优雅拼色\",\"tagName\":\"简约拼色大檐编织帽\",\"soldOut\":0,\"cart\":false,\"itemId\":1147016,\"picUrl\":\"http://yanxuan.nosdn.127.net/e7ee5f712a8babd470368e38cd025556.png\",\"itemName\":\"简约拼色大檐编织帽\",\"top\":218,\"left\":426,\"price\":\"119.00\",\"itemStatus\":2,\"invalid\":0,\"id\":0,\"position\":2}],\"height\":666}",
    "title": "",
    "topicId": 1033,
    "topicTagId": 0,
    "topicTemplateId": 0,
    "type": -1,
    "typeName": ""
  },
  "yxWeek": [],
  "zhenOne": {
    "avatar": "http://yanxuan.nosdn.127.net/dc1b60a9c6d45c743838d55a50826424.png",
    "color": "",
    "commentSwitch": false,
    "content": "",
    "itemPicUrl": "",
    "leftTopTag": "",
    "linkUrl": "",
    "nickname": "口碑商品",
    "period": "",
    "picList": [],
    "picUrl": "https://yanxuan.nosdn.127.net/1b0f7ea3eb5a085ebca5408a00e9e373.jpg",
    "priceInfo": 109,
    "readCount": "",
    "scenePicUrl": "",
    "schemeUrl": "http://m.you.163.com/topic/v1/pub/zeVapieL6u.html",
    "subTitle": "四季床品挑选指南",
    "subtitle": "",
    "tagInfo": "",
    "title": "买对床品，才能夜夜好梦",
    "topicId": 582,
    "topicTagId": 0,
    "topicTemplateId": 0,
    "type": 3,
    "typeName": "口碑商品"
  },
  "zhenThree": {
    "avatar": "http://yanxuan.nosdn.127.net/93cf2f5a47dfc8fcbf2eec0212367fab.png",
    "color": "",
    "commentSwitch": false,
    "content": "",
    "itemPicUrl": "",
    "leftTopTag": "",
    "linkUrl": "",
    "nickname": "特色系列",
    "period": "",
    "picList": [],
    "picUrl": "https://yanxuan.nosdn.127.net/11f0362dd989f07f01238601042139dd.jpg",
    "priceInfo": 359,
    "readCount": "",
    "scenePicUrl": "",
    "schemeUrl": "http://m.you.163.com/topic/v1/pub/eEhRbMwde6.html",
    "subTitle": "珐琅铸铁锅，华美耐用",
    "subtitle": "",
    "tagInfo": "",
    "title": "每个大厨都有的万能锅",
    "topicId": 631,
    "topicTagId": 0,
    "topicTemplateId": 0,
    "type": 4,
    "typeName": "特色系列"
  },
  "zhenTwo": {
    "avatar": "http://yanxuan.nosdn.127.net/35b2729f90d05b5b9568dc87807e4550.png",
    "color": "",
    "commentSwitch": false,
    "content": "",
    "itemPicUrl": "",
    "leftTopTag": "",
    "linkUrl": "",
    "nickname": "特色系列",
    "period": "",
    "picList": [],
    "picUrl": "https://yanxuan.nosdn.127.net/94fc7239d0e08ef858f2a03ad823c24f.jpg",
    "priceInfo": 19.9,
    "readCount": "",
    "scenePicUrl": "",
    "schemeUrl": "http://m.you.163.com/topic/v1/pub/bWLk0HQbW7.html",
    "subTitle": "真正的无化学染色，一切颜色来自天然",
    "subtitle": "",
    "tagInfo": "",
    "title": "给宝宝穿上可以吃的衣服",
    "topicId": 1019,
    "topicTagId": 0,
    "topicTemplateId": 0,
    "type": 4,
    "typeName": "特色系列"
  }
}

export default Model
